### PR TITLE
Updating code to work for silex 2.0-dev and pimple 3.0

### PR DESCRIPTION
**Pull request by ragboyjr**
I've updated the library and tests to work with silex-2.0-dev and pimple 3.0

### CODE REVIEW

**Comment by futurevision** [comment]
+1

**Comment by nrk** [comment]
Hi @ragboyjr and sorry for the humungus delay, do these changes still apply to the current development version of Silex? I'm asking because I've been a bit out-of-the-loop in things related to Silex.

**Comment by ragboyjr** [comment]
@nrk, well, I'm pretty sure there's been a push to have providers depend on `pimple/pimple` and `silex/api` instead of the entire `silex/silex`.

**Comment by bjornpost** [comment]
@nrk would you mind pulling and releasing this?

**Comment by MarcosSegovia** [comment]
Hi @nrk is there any problem in merging this? would be nice to have it working.

**Comment by nrk** [comment]
Not sure about pushing a release yet but at least these changes now live in the [`master` branch](https://github.com/nrk/PredisServiceProvider/tree/master) (aliased to `2.0.x-dev` using composer). The currently stable code will be maintained on the [`v1.0` branch](https://github.com/nrk/PredisServiceProvider/tree/v1.0) which is also the new default branch of the repository.

**Comment by nrk** [comment]
By the way since this service provider doesn't depend on Silex anymore but it simply requires Pimple we could even rename the namespace from Predis\Silex to Predis\Pimple... not really sure yet, it's just a thought for now.

**Pull request merged**
